### ISSUE TITLE
Doesn't reload when source files are changed

### ISSUE THREAD

**Issue by nickretallack** [dantebronto/picard#2]
Run Picard and it seems to daemonify itself.  If you make any changes to your source code, it doesn't detect this and reload the app.  To get it to reload, it looks like you have to find and kill the process manually.  Not a fun way to develop.

**Comment by aeosynth** [comment]
I run picard (node) and vim inside of screen, so to show new changes I execute:

:w<CR>^A^A^C^P<CR>

:w<CR> to save the file in vim

^A^A to switch to picard process

^C kill process

^P<CR> select and run last bash command (the node / picard process).

It works.

**Comment by horatio-sans-serif** [comment]
I think nickretallack was hoping that picard would auto-detect file changes and reload the file.

**Comment by nickretallack** [comment]
Automatic reloading would be nice, but it may make things difficult with Node.js, which appears to allow you to save a lot of stateful information in the server.  It would be fine to just make it easier to kill and restart the server though.  Your workflow implies that node is the only thing you run in screen, which wont work for me.  An inter-process signal might be a better way to implement server restarting.

**Comment by dantebronto** [comment]
I don't want to commit it, because it's kind of a hack, but check out the way I take care of this here: http://gist.github.com/319058. If you're doing TDD, it makes it pretty simple to automatically restart the server when running your test suite.

I agree it would be nice if Picard auto-restarted, but for the time being this is more a problem with node.js. Hoping someone comes up with a better solution.

**Comment by dantebronto** [comment]
Although I haven't tried it yet, it looks like the nodules library solves this issue.
